"""Create games and user_games tables

Revision ID: 7c618312b09e
Revises: 73e046dc6e08
Create Date: 2026-08-13 11:19:09.507996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c618312b09e'
down_revision: Union[str, Sequence[str], None] = '73e046dc6e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_achievements', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_appid'), 'games', ['appid'], unique=True)
    op.create_table('user_games',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('achievements_unlocked', sa.Integer(), nullable=False),
    sa.Column('is_platinum', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('platinum_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_games')
    op.drop_index(op.f('ix_games_appid'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
